//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class chat_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.DataList DataList1;
protected global::System.Web.UI.WebControls.Label Label1;
protected global::System.Web.UI.ScriptManager scr;
protected global::System.Web.UI.Timer Timer1;
protected global::System.Web.UI.WebControls.DataList DataList2;
protected global::System.Web.UI.UpdatePanel UpdatePanel1;
protected global::System.Web.UI.WebControls.TextBox TextBox1;
protected global::System.Web.UI.WebControls.Button Button1;
protected global::System.Web.UI.WebControls.PlaceHolder ChatControls;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control3(object sender, System.EventArgs e) {
System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
System.Web.UI.WebControls.DataListItem Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
Container = ((System.Web.UI.WebControls.DataListItem)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 1 "C:\Users\Shatvikashadvini\AppData\Local\Temp\F18EFE4C466EC2FAF3E0A3369327D90B8539\3\LostAndFound\LostAndFound\Chat.aspx"
@__o =  Bind("name") ;

#line default
#line hidden

#line 2 "C:\Users\Shatvikashadvini\AppData\Local\Temp\F18EFE4C466EC2FAF3E0A3369327D90B8539\3\LostAndFound\LostAndFound\Chat.aspx"
@__o =  Bind("uid") ;

#line default
#line hidden
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public void @__DataBinding__control6(object sender, System.EventArgs e) {
System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
System.Web.UI.WebControls.DataListItem Container;
object @__o;
dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
Container = ((System.Web.UI.WebControls.DataListItem)(dataBindingExpressionBuilderTarget.BindingContainer));

#line 3 "C:\Users\Shatvikashadvini\AppData\Local\Temp\F18EFE4C466EC2FAF3E0A3369327D90B8539\3\LostAndFound\LostAndFound\Chat.aspx"
@__o =  Bind("Message") ;

#line default
#line hidden

#line 4 "C:\Users\Shatvikashadvini\AppData\Local\Temp\F18EFE4C466EC2FAF3E0A3369327D90B8539\3\LostAndFound\LostAndFound\Chat.aspx"
@__o =  Eval("Sender").ToString().Equals(Session["name"].ToString(), StringComparison.OrdinalIgnoreCase) ? "sender-message" : "receiver-message" ;

#line default
#line hidden
}
}
}
