//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class lostitems_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Repeater userRepeater;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control3(object sender, System.EventArgs e) {
System.Web.UI.WebControls.RepeaterItem Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));

#line 1 "C:\Users\Shatvikashadvini\AppData\Local\Temp\E72FF1F20AF38DDF2182AC4BC411D4A67D84\4\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Convert.ToBase64String((byte[])Eval("l_img")) ;

#line default
#line hidden

#line 2 "C:\Users\Shatvikashadvini\AppData\Local\Temp\E72FF1F20AF38DDF2182AC4BC411D4A67D84\4\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("lname") ;

#line default
#line hidden

#line 3 "C:\Users\Shatvikashadvini\AppData\Local\Temp\E72FF1F20AF38DDF2182AC4BC411D4A67D84\4\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("ldesc") ;

#line default
#line hidden

#line 4 "C:\Users\Shatvikashadvini\AppData\Local\Temp\E72FF1F20AF38DDF2182AC4BC411D4A67D84\4\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("llostAt") ;

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class lostitems_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.Repeater userRepeater;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
public void @__DataBind__control3(object sender, System.EventArgs e) {
System.Web.UI.WebControls.RepeaterItem Container;
System.Web.UI.DataBoundLiteralControl target;
object @__o;
target = ((System.Web.UI.DataBoundLiteralControl)(sender));
Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));

#line 1 "C:\Users\Shatvikashadvini\AppData\Local\Temp\D240A7437A596E3D3B360E64ED4DB0F03718\3\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Convert.ToBase64String((byte[])Eval("l_img")) ;

#line default
#line hidden

#line 2 "C:\Users\Shatvikashadvini\AppData\Local\Temp\D240A7437A596E3D3B360E64ED4DB0F03718\3\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("lname") ;

#line default
#line hidden

#line 3 "C:\Users\Shatvikashadvini\AppData\Local\Temp\D240A7437A596E3D3B360E64ED4DB0F03718\3\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("ldesc") ;

#line default
#line hidden

#line 4 "C:\Users\Shatvikashadvini\AppData\Local\Temp\D240A7437A596E3D3B360E64ED4DB0F03718\3\LostAndFound\LostAndFound\LostItems.aspx"
@__o =  Eval("llostAt") ;

#line default
#line hidden
}
}
}
